### ISSUE TITLE
async function "SyntaxError: Unexpected token function"

### ISSUE THREAD

**Issue by effbiae** [schopenhauer/ig-markets#10]
```
$ nodejs --harmony example.js 
/home/jack/ig/ig-markets-master/lib/ig.js:41
IG.prototype._request = async function (method, action, data = null, version = 2, attempt = 0) {
                              ^^^^^^^^

SyntaxError: Unexpected token function
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/jack/ig/ig-markets-master/example.js:1:72)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

```

**Comment by ottosson** [comment]
Have you installed using npm?

> npm install ig-markets --save

**Comment by cam861** [comment]
@effbiae You might be running the LTS version of Node (6.x) which doesn't support async functions out of the box.  This commit PR  #4 removed the third party `async` library and makes mention of the use of the `--harmony` flag when running node.

Alternatively, tanspiling using `babel` or similar might be a suitable option.

**Comment by adriandialog** [comment]
@effbiae I had the same issue, but after installing babel-cli ( ```$npm install --save-dev babel-cli ``` and then ```$npm install --save-dev babel-preset-es2015 babel-preset-es2017```) and created a .babelrc file in the root folder with the content :``` { "presets": ["es2015","es2017"] }```. In the cmd just type ```babel-node example.js``` and it should work fine.
