### ISSUE TITLE
Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

### ISSUE THREAD

**Issue by effbiae** [schopenhauer/ig-markets#9]
$ nodejs --version
v4.2.6
ig-markets-master$ nodejs example.js 
/home/jack/ig/ig-markets-master/lib/ig.js:3
let API = 'https://api.ig.com/gateway/deal/';
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/jack/ig/ig-markets-master/example.js:1:72)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

**Comment by ottosson** [comment]
You should use a newer version of Node, or transpile to es5 using Babel or similar.
